[package]
name = "rwnew"
version = "0.1.0"
edition = "2021"

[dependencies]

byteorder = "1.5.0"
tokio = { version = "1.36.0", features = ["fs", "net", "io-util", "rt-multi-thread", "macros", "sync", "rt"] }
anyhow = "1.0.95"